# Generated by Django 5.1.3 on 2025-01-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuchnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('month_added', models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Skladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('weganin', models.BooleanField(default=True)),
                ('bezglutenowe', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=500)),
                ('pseudonim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NarzedzieKuchenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('odpowiednie_dla', models.ManyToManyField(blank=True, related_name='narzedzia_kuchenne', to='folder_aplikacji.kuchnia')),
            ],
        ),
        migrations.CreateModel(
            name='PreferencjeDietetyczne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weganin', models.BooleanField(default=False)),
                ('wegetarianin', models.BooleanField(default=False)),
                ('bezglutenowe', models.BooleanField(default=False)),
                ('alergie', models.TextField(blank=True, null=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencje_dietetyczne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Przepis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('difficulty_levels', models.CharField(choices=[('P', 'PROSTY'), ('S', 'ŚREDNI'), ('T', 'TRUDNY')], default='P', max_length=1)),
                ('instrukcje', models.TextField()),
                ('czas_przygotowania', models.PositiveIntegerField(help_text='Czas przygotowania w minutach')),
                ('czas_gotowania', models.PositiveIntegerField(help_text='Czas gotowania w minutach')),
                ('porcje', models.PositiveIntegerField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_aktualizacji', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='przepisy', to=settings.AUTH_USER_MODEL)),
                ('kuchnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przepisy', to='folder_aplikacji.kuchnia')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('komentarz', models.TextField(blank=True, null=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzje', to='folder_aplikacji.przepis')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrzepisSkladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.CharField(help_text='Ilość składnika (np. 2 łyżki)', max_length=100)),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_aplikacji.przepis')),
                ('skladnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_aplikacji.skladnik')),
            ],
        ),
        migrations.AddField(
            model_name='przepis',
            name='skladniki',
            field=models.ManyToManyField(related_name='przepisy', through='folder_aplikacji.PrzepisSkladnik', to='folder_aplikacji.skladnik'),
        ),
        migrations.CreateModel(
            name='UlubionePrzepisy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('przepis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulubione_przez', to='folder_aplikacji.przepis')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulubione_przepisy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
