# Generated by Django 5.1.3 on 2025-01-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='kategoria',
            field=models.CharField(default='Brak kategorii', max_length=100),
        ),
    ]
