# Generated by Django 5.1.3 on 2025-01-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0003_alter_przepis_czas_przygotowania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przepis',
            name='czas_gotowania',
            field=models.PositiveIntegerField(blank=True, help_text='Czas gotowania w minutach', null=True),
        ),
        migrations.AlterField(
            model_name='przepis',
            name='czas_przygotowania',
            field=models.PositiveIntegerField(blank=True, help_text='Czas przygotowania w minutach', null=True),
        ),
    ]
