# Generated by Django 5.1.3 on 2025-01-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0004_alter_przepis_czas_gotowania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przepis',
            name='kategoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='przepis',
            name='kuchnia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='przepisy', to='folder_aplikacji.kuchnia'),
        ),
        migrations.AlterField(
            model_name='przepis',
            name='porcje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przepis',
            name='skladniki',
            field=models.ManyToManyField(blank=True, related_name='przepisy', through='folder_aplikacji.PrzepisSkladnik', to='folder_aplikacji.skladnik'),
        ),
    ]
