# Generated by Django 5.1.3 on 2025-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0005_alter_przepis_kategoria_alter_przepis_kuchnia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='przepis',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
