# Generated by Django 5.1.3 on 2025-01-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0006_przepis_obrazek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencjedietetyczne',
            name='uzytkownik',
        ),
        migrations.RemoveField(
            model_name='recenzja',
            name='przepis',
        ),
        migrations.RemoveField(
            model_name='recenzja',
            name='uzytkownik',
        ),
        migrations.DeleteModel(
            name='NarzedzieKuchenne',
        ),
        migrations.DeleteModel(
            name='PreferencjeDietetyczne',
        ),
        migrations.DeleteModel(
            name='Recenzja',
        ),
    ]
